In [233]:
import pandas as pd

In [234]:
df=pd.read_csv('/home/sanglap/Desktop/ML/Data Set/loan_dataset.csv')

In [235]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [236]:
df.shape

(614, 13)

In [237]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [238]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [239]:
# df['Gender'].fillna('Male', inplace=True)
# df['Married'].fillna('Yes', inplace=True)
# df['Dependents'].fillna('0', inplace=True)
# df['LoanAmount'].fillna(df['LoanAmount'].mode()[0], inplace=True)
# df['Self_Employed'].fillna('No', inplace=True)
# df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode()[0], inplace=True)
# df['Credit_History'].fillna(1.0, inplace=True)



df=df.dropna()

In [240]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y

In [241]:
df['Loan_Status']=df['Loan_Status'].map({'Y':1 , 'N': 0})
df['Self_Employed']=df['Self_Employed'].map({'Yes':1, 'No':0})
df['Married']=df['Married'].map({'Yes':1,'No':0})
df['Education']=df['Education'].map({'Graduate':1,'Not Graduate':0})
df['Gender']=df['Gender'].map({'Male':1,'Female':0})
df['Property_Area']=df['Property_Area'].map({'Urban':2,'Rural':0,'Semiurban':1})

df['Dependents']=df['Dependents'].map({'1':1,'3+': 4, '2':2,'0':0})

In [242]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,0
2,LP001005,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,2,1
3,LP001006,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,2,1
4,LP001008,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,2,1
5,LP001011,1,1,2,1,1,5417,4196.0,267.0,360.0,1.0,2,1

In [243]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [244]:
df.shape

(480, 13)

In [245]:
df['Dependents'].value_counts()

Dependents
0    274
2     85
1     80
4     41
Name: count, dtype: int64

In [246]:
from sklearn.model_selection import train_test_split

In [247]:
X = df.drop(columns=['Loan_ID', 'Loan_Status'])
Y = df['Loan_Status']

# Scale numeric features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
numeric_cols = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term']
X[numeric_cols] = scaler.fit_transform(X[numeric_cols])

In [248]:
print(Y)

1      0
2      1
3      1
4      1
5      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 480, dtype: int64

In [260]:
X_train,X_test, Y_train,Y_test=train_test_split(X,Y, test_size=0.1,stratify=Y, random_state=5)

In [261]:
print(Y)

1      0
2      1
3      1
4      1
5      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 480, dtype: int64

In [262]:
print(X)

     Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
1         1        1           1          1              0        -0.137970
2         1        1           0          1              1        -0.417536
3         1        1           0          0              0        -0.491180
4         1        0           0          1              0         0.112280
5         1        1           2          1              1         0.009319
..      ...      ...         ...        ...            ...              ...
609       0        0           0          1              0        -0.435196
610       1        1           4          1              0        -0.222210
611       1        1           1          1              0         0.478206
612       1        1           2          1              0         0.391846
613       0        0           0          1              1        -0.137970

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1            -0.027952   -0.208089          0.275542             1.0
2            -0.604633   -0.979001          0.275542             1.0
3             0.297100   -0.307562          0.275542             1.0
4            -0.604633   -0.046446          0.275542             1.0
5             0.999978    1.520245          0.275542             1.0
..                 ...         ...               ...             ...
609          -0.604633   -0.916831          0.275542             1.0
610          -0.604633   -1.302286         -2.487549             1.0
611          -0.512854    1.346168          0.275542             1.0
612          -0.604633    0.525520          0.275542             1.0
613          -0.604633   -0.145919          0.275542             0.0

     Property_Area
1                0
2                2
3                2
4                2
5                2
..             ...
609              0
610              0
611              2
612              2
613              1

[480 rows x 11 columns]

In [263]:
print(df['Dependents'].unique())

[1 0 2 4]

In [264]:
from sklearn import svm
from sklearn.metrics import accuracy_score

In [265]:
model=svm.SVC(kernel='linear')

In [266]:
model.fit(X_train,Y_train)

SVC(kernel='linear')

In [267]:
training= model.predict(X_train)
train_acc=accuracy_score(training,Y_train)
print("The training data accuracy is : ",train_acc)

testing=model.predict(X_test)
testing_acc=accuracy_score(testing,Y_test)
print("The testing data accuracy is : ",testing_acc)

The training data accuracy is :  0.8055555555555556
The testing data accuracy is :  0.8333333333333334

In [268]:
import pickle

# Suppose your model is called 'model'
with open('loan_model.pkl', 'wb') as f:
    pickle.dump(model, f)

In [269]:


with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

In [270]:
model_features = X.columns.tolist()

import pickle
with open('model_features.pkl', 'wb') as f:
    pickle.dump(model_features, f)